project_id = "jgpffcjktwsohfyljtsg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.receive-whatsapp-message]
    verify_jwt = false
  [functions.send-booking-confirmation]
    verify_jwt = true
  [functions.send-promotional-email]
    verify_jwt = true
  [functions.send-subscription-reminder]
    verify_jwt = false
  [functions.send-whatsapp-notification]
    verify_jwt = true
  [functions.webhook-dispatcher]
    verify_jwt = true
